
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.UI
{
public sealed partial class UIFormConfig : Luban.BeanBase
{
    public UIFormConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        UIFormId = (UIFormId)_buf.ReadInt();
        AssetPath = _buf.ReadString();
        PauseCoveredUIForm = _buf.ReadBool();
        UIGroupName = _buf.ReadString();
    }

    public static UIFormConfig DeserializeUIFormConfig(ByteBuf _buf)
    {
        return new UI.UIFormConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly UIFormId UIFormId;
    /// <summary>
    /// 资源名
    /// </summary>
    public readonly string AssetPath;
    /// <summary>
    /// 遮挡是否暂停
    /// </summary>
    public readonly bool PauseCoveredUIForm;
    /// <summary>
    /// 处于哪个组
    /// </summary>
    public readonly string UIGroupName;
   
    public const int __ID__ = 1938393076;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "UIFormId:" + UIFormId + ","
        + "AssetPath:" + AssetPath + ","
        + "pauseCoveredUIForm:" + PauseCoveredUIForm + ","
        + "UIGroupName:" + UIGroupName + ","
        + "}";
    }
}
}

