
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Entity
{ 
    public enum EntityId
    {
        /// <summary>
        /// 猫猫
        /// </summary>
        Cat = 0,
        /// <summary>
        /// 感叹号
        /// </summary>
        GanTan = 1,
        /// <summary>
        /// 愤怒
        /// </summary>
        Anger = 2,
        /// <summary>
        /// 闪电球
        /// </summary>
        LightningBall = 3,
    }

} 

