
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Entity
{
public sealed partial class EntityConfig : Luban.BeanBase
{
    public EntityConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        EntityId = (Entity.EntityId)_buf.ReadInt();
        AssetPath = _buf.ReadString();
        EntityGroupName = _buf.ReadString();
        Priority = _buf.ReadInt();
    }

    public static EntityConfig DeserializeEntityConfig(ByteBuf _buf)
    {
        return new Entity.EntityConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 实体名称
    /// </summary>
    public readonly Entity.EntityId EntityId;
    /// <summary>
    /// 路径
    /// </summary>
    public readonly string AssetPath;
    /// <summary>
    /// 处于哪个组
    /// </summary>
    public readonly string EntityGroupName;
    /// <summary>
    /// 优先级
    /// </summary>
    public readonly int Priority;
   
    public const int __ID__ = 1714530608;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "EntityId:" + EntityId + ","
        + "AssetPath:" + AssetPath + ","
        + "EntityGroupName:" + EntityGroupName + ","
        + "Priority:" + Priority + ","
        + "}";
    }
}
}

