
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum UIFormId
    {
        /// <summary>
        /// 主菜单
        /// </summary>
        MenuForm = 0,
        /// <summary>
        /// 游戏界面
        /// </summary>
        MainForm = 1,
        /// <summary>
        /// 设置界面
        /// </summary>
        SettingForm = 2,
        /// <summary>
        /// 结束界面
        /// </summary>
        GameOver = 3,
    }

} 

